# Generated by Django 3.0.7 on 2020-07-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosts',
            name='id',
        ),
        migrations.AddField(
            model_name='hosts',
            name='host_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
