# Generated by Django 3.0.8 on 2020-08-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostType',
            fields=[
                ('type_id', models.CharField(max_length=110, primary_key=True, serialize=False)),
                ('host_type', models.CharField(max_length=50)),
                ('host_sub_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='HType',
        ),
    ]
