# Generated by Django 3.0.8 on 2020-08-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_type', models.CharField(max_length=50)),
                ('host_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('host_port', models.IntegerField()),
                ('host_ip', models.GenericIPAddressField()),
                ('passwd', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HostType',
            fields=[
                ('type_id', models.CharField(max_length=110, primary_key=True, serialize=False)),
                ('host_type', models.CharField(max_length=50)),
                ('host_sub_type', models.CharField(max_length=50)),
            ],
        ),
    ]
