# Generated by Django 3.0.7 on 2020-07-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_type', models.CharField(max_length=50)),
                ('host_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('host_port', models.IntegerField()),
                ('host_ip', models.GenericIPAddressField()),
                ('passwd', models.CharField(max_length=50)),
            ],
        ),
    ]
