# Generated by Django 3.0.7 on 2020-07-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=50)),
                ('task_type', models.CharField(max_length=50)),
                ('latest_status', models.CharField(max_length=50)),
                ('create_time', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('update_time', models.CharField(max_length=50)),
                ('task_uuid', models.UUIDField()),
            ],
        ),
    ]
