# Generated by Django 3.0.7 on 2020-07-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_id',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_uuid',
            field=models.UUIDField(auto_created=True, default='f453b1ccc97e4b9d9f20f130421e69af', editable=False, primary_key=True, serialize=False),
        ),
    ]
