# Generated by Django 3.0.8 on 2020-08-07 02:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20200730_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
